import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButton from "@/components/auth-buttons";
import { HomeIcon } from "lucide-react";

import { Noto_Sans_KR } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// const popins = Poppins({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Firebase Nextjs Studio",
  description: "Generated by hotjava.com",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.variable} antialiased`}>
        <AuthProvider>
          <nav className="flex h-24 items-center justify-between bg-sky-950 p-5 text-white">
            <Link
              className="flex items-center gap-2 text-3xl uppercase tracking-widest"
              href="/"
            >
              <HomeIcon size={24} />
              <span>Home</span>
            </Link>
            <ul className="flex items-center gap-6">
              <li>
                <Link
                  href="/property-search"
                  className="uppercase tracking-widest hover:underline"
                >
                  Property search
                </Link>
              </li>
              <li>
                <AuthButton />
              </li>
            </ul>
          </nav>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
